# Generated by Django 4.0.5 on 2022-08-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_profilepoint_dodatkowepunkty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepoint',
            name='color1',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color10',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color11',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color12',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color13',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color14',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color15',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color16',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color17',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color18',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color19',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color2',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color20',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color21',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color22',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color23',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color24',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color25',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color26',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color27',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color28',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color29',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color3',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color30',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color31',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color32',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color33',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color34',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color4',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color5',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color6',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color7',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color8',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color9',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilepoint',
            name='color_dodatkowe_punkty',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], default=0, max_length=200, null=True),
        ),
    ]
