# Generated by Django 4.0.5 on 2022-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_profilepoint_color1_profilepoint_color10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepoint',
            name='color1',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color10',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color11',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color12',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color13',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color14',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color15',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color16',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color17',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color18',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color19',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color2',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color20',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color21',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color22',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color23',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color24',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color25',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color26',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color27',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color28',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color29',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color3',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color30',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color31',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color32',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color33',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color34',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color4',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color5',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color6',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color7',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color8',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color9',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='color_dodatkowe_punkty',
            field=models.CharField(blank=True, choices=[('Zółty', 'Zółty'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='dodatkowepunkty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka26',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka27',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka28',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka29',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka31',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka32',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka33',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka34',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepoint',
            name='kolejka9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
